


# tiers of country
tier1_country = ["United States","United Kingdom","Canada","Australia","France","Germany","Italy","Spain","Netherlands","Belgium","Sweden","Japan","Singapore","Ireland","Portugal","Austria","Switzerland","New Zealand"]
tier2_country = ["Russia","Poland","United Arab Emirates","Thailand","Greece","Croatia","Romania","Oman","Albania","Kuwait","Taiwan","Qatar","Saudi Arabia","South Africa","Israel","Nepal","Colombia","Lithuania","Bulgaria","Venezuela","Morocco","Kenya","Ecuador","China","Cyprus","Kazakhstan","Jamaica","Peru","Mauritius","Maldives","Chile","Slovak Republic","Serbia","Sri Lanka","Jordan","Portugal","Angola","Trinidad & Tobago","Slovenia","Nigeria","Guyana","Honduras","Ghana","Netherlands Antilles","Iran","Brazil","Bangladesh","Costa Rica","Malta","Nicaragua","Montenegro","Bahrain","Latvia","Uzbekistan","Ukraine","Georgia","Turkey","Czech Republic","Egypt","Philippines","Bosnia & Herzegovina","Hungary","Lebanon","Korea, Republic Of","Uruguay","Algeria","Armenia","Pakistan","Cambodia","Cameroon","Vietnam, Democratic Rep. Of","Mexico","Dominican Repulic","Indonesia","Gautemala","Moldova, Republic Of","Belize","Palestine State","Fiji","Brunei"]
tier3_country = ["Somalia","Senegal","Djibouti","Madagascar","Tanzania","Azarbaijan","Reunion","Sierra Leona","Gambia","El Salvador","Ethiopia","Yemen, Democratic","Mozambique","Benin","Liberia","Macedonia,The Former Yugoslav Republic Of","Cape Verde Islands","Mauritania","Congo, The Democratic Republic Of The","Guinea","Bhutan","Cote D Ivoire","Togo","French Guyana","Tajikistan","Guinea Bissau","Surinam","Congo","Syria","Kyrghystan","Burkina Faso","Mali","French Polynesia","Martinique","Gabon","Comoros","Afghanistan","Turkmenistan","Malawi","Seychelles","Barbados"]



# continent of foreign countries
Africa=["Mombasa","Port Louis","Berbera","Tema","Bingazi (Benghazi)","Misurata","Tripoli","Bata","Dar Es Salaam","Longoni","Dakar","Tamatave (Toamasina)","Nacala","Mogadishu","Monrovia","Banjul","Freetown","Toamasina","Pointe Des Galets","Praia","Nouakchott","Victoria","Douala","Matadi","Durban","Moroni","Lome","Port Sudan","Pointe Noire","Cape Town","Casablanca","Djibouti","Majunga (Mahajanga)","Port Harcourt","Onne","Luanda","Harare","Abidjan","Beira","Tincan/Lagos","Bissau","Accra","Cabinda","Cotonou","Maputo","Alger","Tangier","Apapa","Damietta","Johannesburg","Blantyre","Port Victoria","Nouadhibou","Tanga","Nossi-Be","Nairobi","Libreville","Abidos","Zanzibar","Conakry","Johannesberg","R¿Union","Sokhna"]
Asia=["Bhairawa","Kathmandu","Shanghai","Port Hamad","Jebel Ali","Nepalganj","Muara","Laem Chabang","Dubai","Dammam","Umm Qasr","Pokhara","Shuaiba","Damman",".Nepal","Bangkok","Samste Bhutan","Ho Chi Minh C","Mahendranagar Nepal","Belawan","Sohar","Haiphong","Krishnanagar Nepal","Taichung","Almaty","Janakpur","Seoul - Incheon Int'","Muscat ","Tel Aviv Yafo","Colombo","Abu Dhabi","Samdrup-Jonkhar","Mina Khalifa","Jakarta","Surabaya","Bahrain","Baghdad","Khudzhand","Bishkek (Ex Frunze)","Astana (Ex Tselinogr","Tashkent","Shuwaikh","Erbil International ","Doha","Baku","Aktau","Ashkhabad","Bandar Abbas","Dushanbe","Latakia","Osh","Koh-I-Taftan","Salalah","Ashdod","Phuntsholing","Male","Tanjung Priok","Cat Lai","Ho Chi Minh City","Chittagong","Kaohsiung","Limassol","Batumi","Taipei","Jeddah","Haifa","Naxcivan","Hodeidah","Vladivostok","Beirut","Inchon","Aden","Qingdao Pt","Tabilisi","Lat Krabang","Mersin","Da Nang","Nagoya","Incheon","Busan(Korea)","Palembang","Tan Cang - Cai Mep T","Sharjah","Nagoya ","Phnom Penh","Aqaba Free Zone","Khalifa Bin Salman P","Batam Island","Istanbul","Antalya","Izmir (Smyrna)","Diliskelesi","Semarang","Hakata/Fukuoka","Shimkent","Singapore","Cebu","Yerevan","Sulaimaniyah","Ambarli","Izmit","Iskenderun","Xiangang","Davao","Ho Chi Minh, Vict","Manila North Harbor","Poti","Aqaba (El Akaba)","Keelung (Chilung)","Vung Tau","Hithadhoo","Qingdao"]
Europe= ["Frankfurt/Main Int'L","Augusta","Gdynia","Warsaw","Moscow ","Yelgrad (Beograd)","Zagreb","Leipzig/Halle","Milan","Sheremetyevo","Constanta","London - Heathrow","Montengro","Hamburg","Malta Freeport Distr","London Gatway Port","Bucharest","Rijeka Bakar","Barcelona","Porto","Felixstowe","Thessaloniki","Novorossiysk","Varna","Helsinki ","Lisboa","Cologne ","Lisbon ","Astrakhan","St Petersburg (Ex Le","Klaipeda","Southampton","La Spezia","Sines","Valencia","Kaliningrad","Gioia Tauro","Durres","Antwerpen","San Juan Del Puerto","Leixoes","Cork","Dublin","Gdansk","Ploce","Bar","Piraeus","Burgas","Sremska Mitrovica","Koper","Palermo","Fos Sur Mer","Ravenna","Riga","Rotterdam","Naples(Italy)","Le Havre","Dunkerque","Reni","Opoczno","Marsaxlokk","Bremerhaven","Antwerp Churchill Te","Civitavecchia","Szczecin","Salerno","Napoli","Genoa","Castellon De La Plan","Liverpool","Belfast","Moskva","Stockholm","Helsingborg","Trapani","Budapest","Polace","Belgrade (Beograd)","Heraklion (Iraklion)","Lyon","Bari","Fiorano Modenese","Malta (Valetta)"]
North_America=["New York","Chicago O'Hare Int'L","Atlanta, Hartsfield ","Boston - Logan, Ma","Seattle/Tacoma , Wa","Mexico City","Houston","Pto Moin","Savannah","Vancouver","Calgary","Long Beach","Santo Domingo","Port Everglades","San Juan","Miami, Fl","Miami","Kingston","Ensenada","Caucedo Dominic Rep.","Progreso","Port Of Spain","Balboa","Puerto Cort¿S","Lazaro Cardenas","San Juan Capistrano","Halifax","Puerto Quetzal","Altamira","Seattle","Tesistan","Ecatepec","Pointe-¿-Pitre","St John","Acajutla","Everglades City","Montreal","Pointe A Pierre","Minneapolis","Puerto Caldera","Newark","Vera Cruz","Belize City","Oakland","New York Mills","Mobile","Chicago","Castries","St George","Camden Park","Guadalajara","Mazatlan","Willemstad","Bridgetown","Nashville","Boston","Caldera","Monterrey","Nassau New Providenc","Port Saint John S","Newark Apt/New York","Jacksonville","Denver International","California","Los Angeles","Fort-De-France","Norfolk","Detroit City","Moin Bay (Puerto Lim","Corinto","Toronto","Manzanillo","Veracruz"]
South_America= ["Buenaventura","Itajai","La Guaira","Guayaquil","Barranquilla","Arica","Georgetown","Puerto Cabello","Lirqu¿N","Guanta","Santos","Callao","Paramaribo","Montevideo","Cartagena","Maracaibo","Paranagua","Manaus","Navegantes","Degrad Des Cannes","San Antonio","Posorja","Itapoa","Rio De Janeiro","Valparaiso","Iquique","Marchena"]
Oceania=["Fremantle","Brisbane","Melbourne","Sydney","Adelaide","Lautoka","Papeete","Noumea","Auckland","Suva"]












